version: '3.3'

services:
  keycloak:
    image: jboss/keycloak:12.0.2
    ports:
      - 8888:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm.json
    volumes:
      - ./init/realm.json:/tmp/realm.json